package com.southrail.reservation.payment.service;
import com.fasterxml.jackson.databind.*; import com.southrail.reservation.config.properties.RazorpayProperties; import com.southrail.reservation.entity.payment.*; import com.southrail.reservation.exception.ApiException; import com.southrail.reservation.repository.payment.*; import com.southrail.reservation.service.audit.AuditLogService;
import java.nio.charset.StandardCharsets; import java.security.*; import java.util.HexFormat; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class PaymentWebhookService {
 private final RazorpayProperties config; private final ObjectMapper json; private final PaymentWebhookEventRepository events; private final PaymentRepository payments; private final PaymentRefundRepository refunds; private final AuditLogService audit;
 public PaymentWebhookService(RazorpayProperties c,ObjectMapper j,PaymentWebhookEventRepository e,PaymentRepository p,PaymentRefundRepository r,AuditLogService a){config=c;json=j;events=e;payments=p;refunds=r;audit=a;}
 @Transactional public void receive(byte[] raw,String signature,String suppliedId){String body=new String(raw,StandardCharsets.UTF_8);if(!RazorpaySignatures.verify(body,signature,config.webhookSecret()))throw new ApiException(HttpStatus.BAD_REQUEST,"PAYMENT_SIGNATURE_INVALID","Webhook signature is invalid");try{JsonNode root=json.readTree(raw);String type=root.path("event").asText();String id=(suppliedId==null||suppliedId.isBlank())?hash(raw):suppliedId;if(events.existsByProviderAndEventId("RAZORPAY",id))return;PaymentWebhookEvent event=events.saveAndFlush(PaymentWebhookEvent.received(id,type));JsonNode payment=root.path("payload").path("payment").path("entity");JsonNode refund=root.path("payload").path("refund").path("entity");boolean handled=switch(type){case "payment.authorized","payment.captured","payment.failed"->handlePayment(type,payment);case "refund.processed","refund.failed"->handleRefund(type,refund);default->false;};if(handled){event.processed();audit.log(null,"razorpay-webhook","PAYMENT_WEBHOOK_PROCESSED","PAYMENT","Processed "+type+" event "+id);}else event.ignored();}catch(ApiException e){throw e;}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"MALFORMED_WEBHOOK","Webhook payload is malformed");}}
 private boolean handlePayment(String type,JsonNode node){String order=node.path("order_id").asText();if(order.isBlank())return false;Payment p=payments.findByProviderOrderIdForUpdate(order).orElse(null);if(p==null)return false;String id=node.path("id").asText();if("payment.captured".equals(type)&&(p.getStatus()==PaymentStatus.PENDING||p.getStatus()==PaymentStatus.AUTHORIZED))p.captured(id);else if("payment.authorized".equals(type)&&p.getStatus()==PaymentStatus.PENDING)p.authorized(id);else if("payment.failed".equals(type)&&p.getStatus()==PaymentStatus.PENDING)p.failed(node.path("error_code").asText(null),node.path("error_description").asText(null));return true;}
 private boolean handleRefund(String type,JsonNode node){PaymentRefund r=refunds.findByProviderRefundId(node.path("id").asText()).orElse(null);if(r==null)return false;if("refund.processed".equals(type)&&r.getStatus()!=RefundStatus.PROCESSED){r.processed(node.path("id").asText());Payment p=r.getPayment();if(p.getStatus()==PaymentStatus.REFUND_PENDING)p.transition(r.getAmount().compareTo(p.getAmount())>=0?PaymentStatus.REFUNDED:PaymentStatus.PARTIALLY_REFUNDED);}else if("refund.failed".equals(type)&&r.getStatus()!=RefundStatus.FAILED)r.failed();return true;}
 private String hash(byte[] raw)throws NoSuchAlgorithmException{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw));}
}
