package com.southrail.reservation.payment.service;
import com.southrail.reservation.config.properties.RazorpayProperties; import com.southrail.reservation.entity.payment.*; import com.southrail.reservation.payment.gateway.PaymentGateway; import com.southrail.reservation.repository.payment.PaymentRefundRepository; import com.southrail.reservation.service.audit.AuditLogService;
import java.util.*; import org.slf4j.*; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Component; import org.springframework.transaction.support.TransactionTemplate;
@Component public class RefundDispatcher {
 private static final Logger log=LoggerFactory.getLogger(RefundDispatcher.class); private final PaymentRefundRepository refunds; private final PaymentGateway gateway; private final RazorpayProperties config; private final AuditLogService audit; private final TransactionTemplate tx;
 public RefundDispatcher(PaymentRefundRepository r,PaymentGateway g,RazorpayProperties c,AuditLogService a,TransactionTemplate t){refunds=r;gateway=g;config=c;audit=a;tx=t;}
 @Scheduled(fixedDelayString="${razorpay.refund-poll-delay:60000}") public void dispatch(){if(!config.enabled())return;for(var r:refunds.findTop20ByStatusInOrderByCreatedAt(List.of(RefundStatus.REQUESTED,RefundStatus.FAILED)))try{tx.executeWithoutResult(s->execute(r.getId()));}catch(RuntimeException e){log.warn("refund_dispatch_failed refundId={}",r.getId());}}
 void execute(UUID id){PaymentRefund r=refunds.findByIdForUpdate(id).orElse(null);if(r==null||r.getStatus()==RefundStatus.PROCESSED||r.getPayment().getProviderPaymentId()==null)return;try{var result=gateway.initiateRefund(r.getPayment().getProviderPaymentId(),PaymentService.toMinorUnits(r.getAmount()),r.getIdempotencyKey());if("processed".equals(result.status())){r.processed(result.id());Payment p=r.getPayment();p.transition(r.getAmount().compareTo(p.getAmount())>=0?PaymentStatus.REFUNDED:PaymentStatus.PARTIALLY_REFUNDED);audit.log(r.getBooking().getUser().getId(),r.getBooking().getUser().getEmail(),"REFUND_PROCESSED","PAYMENT","Refund "+r.getId()+" processed for PNR "+r.getBooking().getPnr());}else r.processing(result.id());}catch(RuntimeException e){if(r.getStatus()!=RefundStatus.FAILED)r.failed();audit.log(r.getBooking().getUser().getId(),r.getBooking().getUser().getEmail(),"REFUND_FAILED","PAYMENT","Refund "+r.getId()+" remains retryable");throw e;}}
}
