export const recentSearchKey = 'southrail_recent_searches';

export function getToday() { return new Date().toISOString().slice(0, 10); }
export function stationFromCode(code) { return code ? { code, name: '' } : null; }
export function normalizeStationQuery(value) { const query = String(value || '').trim(); const labelMatch = query.match(/^([A-Za-z0-9]+)\s+-\s+.+$/); return (labelMatch ? labelMatch[1] : query).toUpperCase(); }
export function cleanSearch(values) { return { source: String(values.source || '').trim().toUpperCase(), destination: String(values.destination || '').trim().toUpperCase(), journeyDate: values.journeyDate || '', travelClass: values.travelClass || '3A', quota: values.quota || 'GENERAL' }; }
export function normalizeSearch(values, today) { return { source: String(values.source || '').trim().toUpperCase(), destination: String(values.destination || '').trim().toUpperCase(), journeyDate: values.journeyDate && values.journeyDate >= today ? values.journeyDate : today, travelClass: values.travelClass || '3A', quota: values.quota || 'GENERAL' }; }
export function validateSearch(values, today) { if (!values.source || !values.destination || !values.journeyDate || !values.travelClass || !values.quota) return { title: 'Search could not be completed', message: 'Please check source, destination, date, and class.' }; if (values.source === values.destination) return { title: 'Search could not be completed', message: 'Source and destination cannot be the same.', field: 'destination' }; if (values.journeyDate < today) return { title: 'Search could not be completed', message: 'Please select today or a future journey date.', field: 'journeyDate', actionLabel: "Use today's date", fixDate: true }; return null; }
export function readRecentSearches(today) { try { const parsed = JSON.parse(localStorage.getItem(recentSearchKey) || '[]'); if (!Array.isArray(parsed)) return []; return parsed.map((item) => normalizeSearch(item, today)).filter((item) => item.source && item.destination && item.source !== item.destination).slice(0, 5); } catch { return []; } }
export function saveRecentSearch(search, today) { const current = readRecentSearches(today); const next = [search, ...current.filter((item) => item.source !== search.source || item.destination !== search.destination || item.travelClass !== search.travelClass || item.quota !== search.quota)].slice(0, 5); localStorage.setItem(recentSearchKey, JSON.stringify(next)); return next; }
export function getInitialSearchValues(today) { const recent = readRecentSearches(today)[0]; return recent || { source: '', destination: '', journeyDate: today, travelClass: '3A', quota: 'GENERAL' }; }
export function sortResults(results) { return [...(results || [])].sort((a, b) => { const aSeats = Number(a.availableSeats || 0); const bSeats = Number(b.availableSeats || 0); if ((aSeats > 0) !== (bSeats > 0)) return aSeats > 0 ? -1 : 1; const timeCompare = minutesFromTime(a.departureTime) - minutesFromTime(b.departureTime); if (timeCompare !== 0) return timeCompare; return Number(a.durationMinutes || 0) - Number(b.durationMinutes || 0); }); }
function minutesFromTime(value) { const [hours = '0', minutes = '0'] = String(value || '00:00').split(':'); return Number(hours) * 60 + Number(minutes); }
export function getAvailabilityStatus(train) { const seats = Number(train.availableSeats || 0); if (seats > 0) return { canBook: true, color: seats < 10 ? 'warning' : 'success', label: seats < 10 ? 'Limited seats' : 'Available', detail: `${seats} seats available` }; const prediction = String(train.prediction || '').trim(); const label = /class not available/i.test(prediction) ? 'Class not available' : 'Sold out'; return { canBook: false, color: 'error', label, detail: prediction && prediction !== label ? prediction : 'Booking is unavailable for this class' }; }
export function formatDuration(minutes) { const total = Number(minutes || 0); const hours = Math.floor(total / 60); const remainingMinutes = total % 60; return `${hours}h ${String(remainingMinutes).padStart(2, '0')}m`; }
export function formatFare(value) { const amount = Number(value); if (!Number.isFinite(amount)) return '₹ -'; return `₹${amount.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`; }
export function formatTime(value) { if (!value) return '--:--'; const [hours = '00', minutes = '00'] = String(value).split(':'); return `${hours.padStart(2, '0')}:${minutes.padStart(2, '0')}`; }
export function toSearchParams(search) { return new URLSearchParams(search).toString(); }
export function fromSearchParams(searchParams, today) { return normalizeSearch(Object.fromEntries(searchParams.entries()), today); }

export function searchKey(search = {}) { return [search.source || '', search.destination || '', search.journeyDate || '', search.travelClass || '', search.quota || ''].join('|'); }
