import { memo } from 'react';
import { Link } from 'react-router-dom';
import { Box, Button, Card, CardContent, Chip, Container, Divider, Grid, Paper, Stack, Tooltip, Typography } from '@mui/material';
import { EmptyState, ErrorState, LoadingState } from '../../../components/StateFeedback.jsx';

export default function HomeResults({ compactSearch, searchIssue, trains, sortedResults, hasResults, onRetry, onUseToday, getAvailabilityStatus, formatFare, formatDuration, getToday }) {
  return (
    <Container maxWidth="xl" sx={{ py: compactSearch ? 3 : 5 }}>
      <Stack spacing={2.5}>
        {searchIssue && <ErrorState title={searchIssue.title} message={searchIssue.message} actionLabel={searchIssue.actionLabel} onAction={searchIssue.actionLabel === "Use today's date" ? onUseToday : undefined} />}
        {!searchIssue && trains.error && <ErrorState title="Search could not be completed" message={trains.error} actionLabel="Retry" onAction={onRetry} />}
        {trains.loading && <LoadingState message="Searching trains..." />}
        {!trains.loading && !searchIssue && !trains.error && trains.hasSearched && !hasResults && <EmptyState title="No trains found" message="No trains are available for this route, date, and class. Try another class, date, or reverse route." />}
        {!trains.loading && !searchIssue && !trains.error && hasResults && <><Box sx={{ px: { xs: 0.5, sm: 0 } }}><Typography variant="h4" fontWeight={900}>Available trains</Typography><Typography color="text.secondary">Choose a train based on fare, duration, and availability.</Typography></Box><RouteComparison results={sortedResults} formatFare={formatFare} formatDuration={formatDuration} /><Grid container spacing={2}>{sortedResults.map((train) => <TrainResultCard key={train.trainId} train={train} search={trains.selectedSearch} getAvailabilityStatus={getAvailabilityStatus} formatFare={formatFare} formatDuration={formatDuration} getToday={getToday} />)}</Grid></>}
      </Stack>
    </Container>
  );
}

const TrainResultCard = memo(function TrainResultCard({ train, search, getAvailabilityStatus, formatFare, formatDuration, getToday }) {
  const availability = getAvailabilityStatus(train); const canBook = availability.canBook;
  const bookingParams = new URLSearchParams({ sourceStationCode: train.sourceCode || search?.source || '', destinationStationCode: train.destinationCode || search?.destination || '', journeyDate: search?.journeyDate || getToday(), travelClass: search?.travelClass || '3A', quota: search?.quota || 'GENERAL' });
  return <Grid item xs={12}><Card className={`sr-result-card ${canBook ? '' : 'sr-result-card--disabled'}`} variant="outlined"><CardContent><Grid container spacing={2} alignItems="center"><Grid item xs={12} md={3}><Typography className="sr-train-number">{train.trainNumber || '-'}</Typography><Typography variant="h6" className="sr-train-name">{train.trainName || 'Train'}</Typography></Grid><Grid item xs={12} md={4}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} alignItems={{ xs: 'stretch', sm: 'center' }} justifyContent="space-between"><StationTime code={train.sourceCode} time={train.departureTime} label="Departure" /><Box className="sr-result-line"><Divider /><Typography variant="caption">{formatDuration(train.durationMinutes)}</Typography></Box><StationTime code={train.destinationCode} time={train.arrivalTime} label="Arrival" align="right" /></Stack></Grid><Grid item xs={12} sm={6} md={2}><Stack spacing={0.75} alignItems={{ xs: 'flex-start', md: 'center' }}><Chip className="sr-availability-chip" size="small" color={availability.color} label={availability.label} /><Typography variant="body2" color="text.secondary">{availability.detail}</Typography></Stack></Grid><Grid item xs={12} sm={6} md={1.5}><Box className="sr-fare-badge"><Typography variant="caption">Fare</Typography><Typography>{formatFare(train.fare)}</Typography><Typography variant="caption">{search?.travelClass || '3A'} / {search?.quota || 'GENERAL'}</Typography></Box></Grid><Grid item xs={12} md={1.5}><Tooltip title={canBook ? '' : 'Booking is unavailable for this train and class.'}><span><Button className="sr-book-now" fullWidth component={canBook ? Link : 'button'} to={canBook ? `/booking/${train.trainId}?${bookingParams.toString()}` : undefined} variant="contained" disabled={!canBook} type="button">Book now</Button></span></Tooltip></Grid></Grid></CardContent></Card></Grid>;
});

function StationTime({ code, time, label, align = 'left' }) { return <Box className="sr-station-time" sx={{ textAlign: { xs: 'center', sm: align } }}><Typography>{code || '-'}</Typography><Typography>{formatTime(time)}</Typography><Typography variant="caption">{label}</Typography></Box>; }
function RouteComparison({ results, formatFare, formatDuration }) { const available = results.filter((item) => Number(item.availableSeats) > 0); const comparable = available.length > 0 ? available : results; const cheapest = comparable.filter((item) => item.fare != null).sort((a, b) => Number(a.fare) - Number(b.fare))[0]; const fastest = comparable.filter((item) => item.durationMinutes != null).sort((a, b) => Number(a.durationMinutes) - Number(b.durationMinutes))[0]; const bestAvailability = available.sort((a, b) => Number(b.availableSeats) - Number(a.availableSeats))[0]; const metrics = [cheapest && { label: 'Cheapest', value: `${cheapest.trainNumber} - ${formatFare(cheapest.fare)}` }, fastest && { label: 'Fastest', value: `${fastest.trainNumber} - ${formatDuration(fastest.durationMinutes)}` }, bestAvailability && { label: 'Best availability', value: `${bestAvailability.trainNumber} - ${bestAvailability.availableSeats} seats` }].filter(Boolean); if (!metrics.length) return null; return <Paper className="sr-route-comparison" variant="outlined"><Grid container spacing={1}>{metrics.map((item) => <Grid item xs={12} sm={4} key={item.label}><Box><Typography color="text.secondary" variant="body2">{item.label}</Typography><Typography fontWeight={800}>{item.value}</Typography></Box></Grid>)}</Grid></Paper>; }
function formatTime(value) { if (!value) return '-'; const [hours = '00', minutes = '00'] = String(value).split(':'); return `${hours.padStart(2, '0')}:${minutes.padStart(2, '0')}`; }
