import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { EmptyState, ErrorState, LoadingState } from '../../../components/StateFeedback.jsx';

export default function PremiumTrainResults({ searchIssue, trains, sortedResults, hasResults, onRetry, onUseToday, getAvailabilityStatus, formatFare, formatDuration, getToday }) {
  return <section className="sr-results-deck" id="results"><div className="sr-section-copy"><span>TRAIN RESULTS</span><h2>Premium departures board</h2></div>{searchIssue && <ErrorState title={searchIssue.title} message={searchIssue.message} actionLabel={searchIssue.actionLabel} onAction={searchIssue.actionLabel === "Use today's date" ? onUseToday : undefined} />}{!searchIssue && trains.error && <ErrorState title="Search could not be completed" message={trains.error} actionLabel="Retry" onAction={onRetry} />}{trains.loading && <LoadingState message="Searching trains..." />}{!trains.loading && !searchIssue && !trains.error && trains.hasSearched && !hasResults && <EmptyState title="No trains found" message="No trains are available for this route, date, and class. Try another class, date, or reverse route." />}{!trains.loading && !searchIssue && !trains.error && hasResults && <div className="sr-premium-results">{sortedResults.map((train, index) => <TrainDeparture key={train.trainId} train={train} search={trains.selectedSearch} getAvailabilityStatus={getAvailabilityStatus} formatFare={formatFare} formatDuration={formatDuration} getToday={getToday} index={index} />)}</div>}</section>;
}
function TrainDeparture({ train, search, getAvailabilityStatus, formatFare, formatDuration, getToday, index }) { const availability = getAvailabilityStatus(train); const canBook = availability.canBook; const bookingParams = new URLSearchParams({ sourceStationCode: train.sourceCode || search?.source || '', destinationStationCode: train.destinationCode || search?.destination || '', journeyDate: search?.journeyDate || getToday(), travelClass: search?.travelClass || '3A', quota: search?.quota || 'GENERAL' }); return <motion.article className={`sr-departure ${canBook ? '' : 'sr-departure--closed'}`} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} viewport={{ once: true }} whileHover={{ y: -6 }}><div className="sr-train-identity"><span>🚆 {train.trainName || 'Train'}</span><strong>{train.trainNumber || '-'}</strong></div><div className="sr-premium-timeline"><Station code={train.sourceCode || search?.source} time={train.departureTime} label="Departure" /><div className="sr-rail-time"><i /><span>{formatDuration(train.durationMinutes)}</span></div><Station code={train.destinationCode || search?.destination} time={train.arrivalTime} label="Arrival" /></div><div className="sr-departure-meta"><div><small>Availability</small><b className={canBook ? 'sr-green' : 'sr-red'}>● {availability.detail}</b></div><div><small>Class</small><b>{search?.travelClass || '3A'}</b></div><div><small>Fare</small><b>{formatFare(train.fare)}</b></div><Link className={`sr-reserve-seat ${canBook ? '' : 'sr-disabled-link'}`} to={canBook ? `/booking/${train.trainId}?${bookingParams.toString()}` : '#'} onClick={(event) => { if (!canBook) event.preventDefault(); }}>{canBook ? 'Reserve Seat' : availability.label}</Link></div></motion.article>; }
function Station({ code, time, label }) { return <div className="sr-station-block"><strong>{formatTime(time)}</strong><span>{code || '-'}</span><small>{label}</small></div>; }
function formatTime(value) { if (!value) return '--:--'; const [hours = '00', minutes = '00'] = String(value).split(':'); return `${hours.padStart(2, '0')}:${minutes.padStart(2, '0')}`; }
